services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/app/proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    restart: always
    depends_on:
      - backend

  backend:
    image: ssfinder-be:latest
    ports:
      - 8080:8080
    container_name: ssfinder-be-container
